[package]
name = "timelines-core"
description = "Core traits and structs for the timelines project."
version = "0.0.1"
edition = "2018"
license = "MIT"

authors = ["Shelby Doolittle <shelby@shelbyd.com>"]

[dependencies]
